version: "3.8"
services:
  db:
    build: ./backendcl/mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  back:
    depends_on:
      - db
    build: ./backendcl/web
    container_name: backend
    environment:
      MYSQL_DATABASE: PTCarvajal
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: database
    ports:
      - "3001:3001"
  front:
    container_name: front
    build: ./frontendcl
    ports:
      - "3000:3000"
    environment:
     SERVER_BACKEND: backend

