version: "3.8"
services:
  db:
    build: ./backendcl/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: PTCarvajal
    restart: always
  web:
    depends_on:
      - db
    build: ./backendcl/web
    environment:
      MYSQL_DATABASE: PTCarvajal
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "3001:3001"
    restart: on-failure

  front:
    build: ./frontendcl
    ports:
      - "3000:3000"